### ISSUE TITLE
Token authentication

### ISSUE THREAD

**Issue by mdebic** [radexperts/adit#18]
## Desired workflow
Users logs into ADIT and can generate a token via the UI. They can manage their tokens via the UI. An admin can also manage all tokens of all users. Token generation should only be availabe for a subset of users, which an admin can manage. This token is later used to authenicate for the REST service.

- [x] Available with Django? If not, what should we use?
- [x] How to integrate with our permissons? Concept?
- [x] How to implement?
- [ ] Optional for now but should be kept in mind: How to restrict token authentication to specific DICOM Servers? New permissons concept necessary?

**Comment by medihack** [comment]
Closed with #42
